apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: staging

commonLabels:
  environment: staging

patches:
  - target:
      kind: Rollout
      name: sample-microservice
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "staging"
